version: '3.8'
services:
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
   image: mcr.microsoft.com/mssql/server
  orderdb:
   image: mcr.microsoft.com/mssql/server
  rabbitmq:
   image: rabbitmq   
volumes:
 catalogdb_volume: 
 identitydb_volume:
 orderdb_volume:
